"""
Order Service - Order operations from OrderTable
Used for G06: Referral Revenue Calculation
"""
from typing import List, Dict, Optional
from .dynamodb_service import db_service


TABLE_NAME = "OrderTable"


def get_orders_by_user(user_id: str) -> List[Dict]:
    """Get all orders for a user."""
    return db_service.query_by_index(
        TABLE_NAME,
        "userIndex",
        "userId",
        user_id
    )


def get_all_orders(limit: int = 100) -> List[Dict]:
    """Get all orders."""
    return db_service.scan_all(TABLE_NAME, limit)


def get_order_revenue_by_user(user_id: str) -> float:
    """Calculate total revenue (grandTotal) from a user's orders."""
    orders = get_orders_by_user(user_id)
    total = sum(float(o.get('grandTotal', 0)) for o in orders)
    return total


def get_referral_revenue_for_user(referrer_user_id: str) -> Dict:
    """
    G06: Calculate total revenue generated by a user's referrals.
    
    Flow:
    1. Get all referrals made by this user from TierReferralTable
    2. For each referred person (sentTo phone), find their userId in UserTable
    3. Get their orders from OrderTable and sum grandTotal
    
    Returns: {
        'total_revenue': float,
        'referrals': [
            {
                'referralName': str,
                'sentTo': str (phone),
                'status': str,
                'bonusEarned': float,
                'userId': str (referred user's ID, if found),
                'orders': int (order count),
                'revenue': float (their total order value)
            }
        ]
    }
    """
    from .referral_service import get_referrals_by_user
    from .user_service import search_users
    
    referrals = get_referrals_by_user(referrer_user_id)
    
    result = {
        'total_revenue': 0,
        'total_referrals': len(referrals),
        'converted_referrals': 0,
        'referrals': []
    }
    
    for ref in referrals:
        referral_info = {
            'referralName': ref.get('referralName', 'Unknown'),
            'sentTo': ref.get('sentTo', ''),
            'status': ref.get('status', 'Unknown'),
            'bonusEarned': float(ref.get('sendedAmount', 0)),
            'userId': None,
            'orders': 0,
            'revenue': 0
        }
        
        # Try to find referred user by phone number
        phone = ref.get('sentTo', '')
        if phone:
            found_users = search_users(phone)
            if found_users:
                referred_user = found_users[0]
                referred_user_id = referred_user.get('userId', '')
                referral_info['userId'] = referred_user_id
                
                # Get their orders
                if referred_user_id:
                    orders = get_orders_by_user(referred_user_id)
                    referral_info['orders'] = len(orders)
                    referral_info['revenue'] = sum(
                        float(o.get('grandTotal', 0)) for o in orders
                    )
                    result['total_revenue'] += referral_info['revenue']
                    
                    if referral_info['orders'] > 0:
                        result['converted_referrals'] += 1
        
        result['referrals'].append(referral_info)
    
    return result
